services:
  #  tribe.api:
  #    image: tribe.api
  #    build:
  #      context: .
  #      dockerfile: Tribe.Api/Dockerfile
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - default
