//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ForbiddenErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForbiddenErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Messenger.Core.Constants.ForbiddenErrorCodes", typeof(ForbiddenErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANT_CHANGE_OWNER_PERMISSIONS.
        /// </summary>
        public static string CantChangeOwnerPermissions {
            get {
                return ResourceManager.GetString("CantChangeOwnerPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANT_EXCLUDE_ADMIN.
        /// </summary>
        public static string CantExcludeAdmin {
            get {
                return ResourceManager.GetString("CantExcludeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT_CHAT_MEMBER.
        /// </summary>
        public static string NotChatMember {
            get {
                return ResourceManager.GetString("NotChatMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT_ENOUGH_PERMISSIONS.
        /// </summary>
        public static string NotEnoughPermissions {
            get {
                return ResourceManager.GetString("NotEnoughPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANT_LEAVE_WHILE_OWNER.
        /// </summary>
        public static string OwnerCantLeaveChannel {
            get {
                return ResourceManager.GetString("OwnerCantLeaveChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAS_BANNED.
        /// </summary>
        public static string WasBanned {
            get {
                return ResourceManager.GetString("WasBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAS_EXCLUDED.
        /// </summary>
        public static string WasExcluded {
            get {
                return ResourceManager.GetString("WasExcluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAS_MUTED.
        /// </summary>
        public static string WasMuted {
            get {
                return ResourceManager.GetString("WasMuted", resourceCulture);
            }
        }
    }
}
